### ISSUE TITLE
support for alpha transparency

### ISSUE THREAD

**Issue by ohs2033** [thenickdude/webm-writer-js#14]
Thanks for great library.

It seems that exporting video with alpha-transparency is not supported yet.

have any plan for supporting alpha transparency?

thanks.

**Comment by thenickdude** [comment]
Hi there,

I've added support for this now, but unfortunately due to the way that Chrome's WebP encoder works, the opacity of the resulting video get scaled down into the range 22-240, so the video can be neither fully-transparent nor fully-opaque :(. Apart from that it works nicely, check out the example in test/transparent/
